/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author filip
 */
public class InsertEvalData extends javax.swing.JFrame {

    /**
     * Creates new form InsertEvalData
     */
    public InsertEvalData() {
        initComponents();
        showEvaluationApplics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton_Back_ = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Evaluations = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(52, 73, 94));

        jButton_Back_.setBackground(new java.awt.Color(242, 38, 19));
        jButton_Back_.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Back_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_Back_.setText("Back");
        jButton_Back_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back_ActionPerformed(evt);
            }
        });

        jTable_Evaluations.setBackground(new java.awt.Color(236, 240, 241));
        jTable_Evaluations.setForeground(new java.awt.Color(52, 73, 94));
        jTable_Evaluations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Evaluations.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable_Evaluations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EvaluationsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Evaluations);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(80, 80, 80)
                .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Back_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back_ActionPerformed
        MenuEvaluator meval = new MenuEvaluator();
        meval.setVisible(true);
        meval.pack();
        meval.setLocationRelativeTo(null);
        meval.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_Back_ActionPerformed

    private void jTable_EvaluationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EvaluationsMouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable_Evaluations.getModel();

        int selectedRow = jTable_Evaluations.getSelectedRow();
        int selectedCol = jTable_Evaluations.getSelectedColumn();             
        
        String subm_date = jTable_Evaluations.getValueAt(selectedRow, 9).toString();       
        String curr_date = java.time.LocalDate.now().toString();
        
        
        if (selectedCol == 5 ) // interview column selected
        {
            String column_value = (String) jTable_Evaluations.getValueAt(selectedRow, selectedCol);
            String ev_id = jTable_Evaluations.getValueAt(selectedRow, 0).toString();             
            
            if(curr_date.compareTo(subm_date) > 0 && column_value == null) {
                
                String[] options = {"0", "1", "2", "3", "4"};
                String grade = (String) JOptionPane.showInputDialog(null, "Interview", "Select grade(0-4):"
                    ,JOptionPane.QUESTION_MESSAGE,null, options, options[0]);
                
                if(grade != null){                   
                    setInterview(ev_id, grade);
                    model.setValueAt(grade, selectedRow, selectedCol);
                    finalizeEvaluationResult(selectedRow);                
                }                       
            }
            else if(curr_date.compareTo(subm_date) < 0 && column_value == null) 
                JOptionPane.showMessageDialog(null, "Submission date not expired yet!");       
        }
        
        if (selectedCol == 6) // report column selected
        {
            String column_value = (String) jTable_Evaluations.getValueAt(selectedRow, selectedCol);
            String ev_id = jTable_Evaluations.getValueAt(selectedRow, 0).toString();              
            
            if(curr_date.compareTo(subm_date) > 0 && column_value == null) {
               
                String[] options = {"0", "1", "2", "3", "4"};
                String grade = (String) JOptionPane.showInputDialog(null, "Report", "Select grade(0-4):"
                    ,JOptionPane.QUESTION_MESSAGE,null, options, options[0]);
                
                if(grade != null){                   
                    setReport(ev_id, grade);
                    model.setValueAt(grade, selectedRow, selectedCol);
                    finalizeEvaluationResult(selectedRow);
                }
            }
            else if(curr_date.compareTo(subm_date) < 0 && column_value == null) 
                JOptionPane.showMessageDialog(null, "Submission date not expired yet!");        
        }
        
        if (selectedCol == 7 ) // extras column selected
        {
            String column_value = (String) jTable_Evaluations.getValueAt(selectedRow, selectedCol);
            String ev_id = jTable_Evaluations.getValueAt(selectedRow, 0).toString();       
       
            if(curr_date.compareTo(subm_date) > 0 && column_value == null) {
                
                String[] options = {"0", "1", "2"};
                String grade =  (String) JOptionPane.showInputDialog(null, "Extras", "Select grade(0-2):"
                    ,JOptionPane.QUESTION_MESSAGE,null, options, options[0]);

                if(grade != null){
                    setExtras(ev_id, grade);
                    model.setValueAt(grade, selectedRow, selectedCol);
                    finalizeEvaluationResult(selectedRow);
                }
            }
            else if(curr_date.compareTo(subm_date) < 0 && column_value == null) 
                JOptionPane.showMessageDialog(null, "Submission date not expired yet!");      
        }
       
    }//GEN-LAST:event_jTable_EvaluationsMouseClicked

    
     private void setInterview(String ev_id, String interv_grade){
        
        CallableStatement cs;
        
        String proc = "{CALL setInterview_grade(?,?)}";    
        
        try {
            cs = MySQLconnection.connectDb().prepareCall(proc);
            
            cs.setString(1, ev_id);
            cs.setString(2, interv_grade);
            
            cs.execute();
            JOptionPane.showMessageDialog(null, "Interview grade added!");
        
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }
    
    
    private void setReport(String ev_id, String report_grade){
       
        CallableStatement cs;
        
        String proc = "{CALL setReport_grade(?,?)}";    
        
        try {
            cs = MySQLconnection.connectDb().prepareCall(proc);
            
            cs.setString(1, ev_id);
            cs.setString(2, report_grade);
            
            cs.execute();
            JOptionPane.showMessageDialog(null, "Report grade added!");
        
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }
    
    private void setExtras(String ev_id, String extras_grade){
        
        CallableStatement cs;
        
        String proc = "{CALL setExtras_grade(?,?)}";    
        
        try {
            cs = MySQLconnection.connectDb().prepareCall(proc);
            
            cs.setString(1, ev_id);
            cs.setString(2, extras_grade);
            
            cs.execute();
            JOptionPane.showMessageDialog(null, "Extras grade added!");
        
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }
    
    private void finalizeEvaluationResult(int selectedRow){
        
        String interview = (String) jTable_Evaluations.getValueAt(selectedRow, 5);
        String report = (String) jTable_Evaluations.getValueAt(selectedRow, 6);
        String extras = (String) jTable_Evaluations.getValueAt(selectedRow, 7);
        String jod_id = jTable_Evaluations.getValueAt(selectedRow, 3).toString();
       
        String evaluator = MenuEvaluator.EvaluatorUsername;
                
        CallableStatement cs;
        
        String proc = "{CALL finalizeEval_3_2(?,?,?,?,?)}";    
        
        try {
            cs = MySQLconnection.connectDb().prepareCall(proc);
            
            cs.setString(1, evaluator);
            cs.setString(2, jod_id);
            cs.setString(3, interview);
            cs.setString(4, report);
            cs.setString(5, extras);
            
            
            cs.execute();
            JOptionPane.showMessageDialog(null, "Evaluation finalized!");
        
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
                
    
    }
    
    private void showEvaluationApplics(){
        
        CallableStatement cs;
        ResultSet res;

        String proc = "{CALL view_evalsApplics(?)}";

        String username = MenuEvaluator.EvaluatorUsername;

        try {
            cs = MySQLconnection.connectDb().prepareCall(proc);

            cs.setString(1, username);
            
            res = cs.executeQuery();
            jTable_Evaluations.setModel(DbUtils.resultSetToTableModel(res));


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
   
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertEvalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertEvalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertEvalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertEvalData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertEvalData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Evaluations;
    // End of variables declaration//GEN-END:variables
}
