/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JComboBox;

/**
 *
 * @author filip
 */
public class MenuAdmin extends javax.swing.JFrame {

    public static String AdminUsername;
    
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelClose3 = new javax.swing.JLabel();
        jLabelMinim3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_Companies = new javax.swing.JRadioButton();
        jRadioButton_Employees_ = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton_Evaluators_ = new javax.swing.JRadioButton();
        jButton_Back_ = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jRadioButton_Managers_ = new javax.swing.JRadioButton();
        jRadioButton_Antikeim = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton_Table = new javax.swing.JRadioButton();
        jRadioButton_User = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(248, 148, 6));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin Menu");

        jLabelClose3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabelClose3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose3.setText("X");
        jLabelClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose3MouseClicked(evt);
            }
        });

        jLabelMinim3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinim3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinim3.setText("-");
        jLabelMinim3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinim3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinim3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jLabelMinim3)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabelClose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMinim3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(52, 73, 94));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Create new account for:");

        jRadioButton_Companies.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_Companies.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_Companies.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_Companies.setText("Companies");
        jRadioButton_Companies.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_Companies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Companies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_CompaniesActionPerformed(evt);
            }
        });

        jRadioButton_Employees_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_Employees_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_Employees_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_Employees_.setText("Employees");
        jRadioButton_Employees_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_Employees_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Employees_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Employees_ActionPerformed(evt);
            }
        });

        jRadioButton_Evaluators_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_Evaluators_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_Evaluators_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_Evaluators_.setText("Evaluators");
        jRadioButton_Evaluators_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_Evaluators_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Evaluators_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Evaluators_ActionPerformed(evt);
            }
        });

        jButton_Back_.setBackground(new java.awt.Color(242, 38, 19));
        jButton_Back_.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Back_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_Back_.setText("Back");
        jButton_Back_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back_ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Insert new:");

        jRadioButton_Managers_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_Managers_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_Managers_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_Managers_.setText("Managers");
        jRadioButton_Managers_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_Managers_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Managers_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_Managers_ActionPerformed(evt);
            }
        });

        jRadioButton_Antikeim.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_Antikeim.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_Antikeim.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_Antikeim.setText("Antikeim");
        jRadioButton_Antikeim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_Antikeim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Antikeim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AntikeimActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("View log file by selecting:");

        jRadioButton_Table.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_Table.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_Table.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_Table.setText("Table");
        jRadioButton_Table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_Table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_Table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_TableActionPerformed(evt);
            }
        });

        jRadioButton_User.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_User.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_User.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_User.setText("User");
        jRadioButton_User.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_UserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButton_Table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_User, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_Companies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_Antikeim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jRadioButton_Employees_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_Evaluators_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_Managers_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Managers_)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Evaluators_)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Employees_)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Companies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Antikeim)
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Table)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_User)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose3MouseClicked
        System.exit(0);

    }//GEN-LAST:event_jLabelClose3MouseClicked

    private void jLabelMinim3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinim3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinim3MouseClicked

    private void jRadioButton_Evaluators_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Evaluators_ActionPerformed
        jRadioButton_Employees_.setSelected(false);
        jRadioButton_Companies.setSelected(false);
        jRadioButton_Antikeim.setSelected(false);
        jRadioButton_Companies.setSelected(false);
        jRadioButton_Table.setSelected(false);
        jRadioButton_User.setSelected(false);
        
        
        EvaluatorRegisterForm evrf = new EvaluatorRegisterForm();
        evrf.setVisible(true);
        evrf.pack();
        evrf.setLocationRelativeTo(null);
        evrf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_Evaluators_ActionPerformed

    private void jRadioButton_CompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_CompaniesActionPerformed
        jRadioButton_Employees_.setSelected(false);
        jRadioButton_Evaluators_.setSelected(false);
        jRadioButton_Managers_.setSelected(false);  
        jRadioButton_Antikeim.setSelected(false);
        jRadioButton_User.setSelected(false);
        jRadioButton_Table.setSelected(false);
        
        CompanyInsert compin = new CompanyInsert();
        compin.setVisible(true);
        compin.pack();
        compin.setLocationRelativeTo(null);
        compin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jRadioButton_CompaniesActionPerformed

    private void jRadioButton_Employees_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Employees_ActionPerformed
        jRadioButton_Managers_.setSelected(false);
        jRadioButton_Evaluators_.setSelected(false);
        jRadioButton_Antikeim.setSelected(false);
        jRadioButton_Companies .setSelected(false);
        jRadioButton_User.setSelected(false);
        jRadioButton_Table.setSelected(false);
             
        EmployeeRegisterForm erf = new EmployeeRegisterForm();
        erf.setVisible(true);
        erf.pack();
        erf.setLocationRelativeTo(null);
        erf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jRadioButton_Employees_ActionPerformed

    private void jButton_Back_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back_ActionPerformed
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_Back_ActionPerformed

    private void jRadioButton_Managers_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Managers_ActionPerformed
        jRadioButton_Evaluators_.setSelected(false);
        jRadioButton_Employees_.setSelected(false);
        jRadioButton_Antikeim.setSelected(false);
        jRadioButton_Companies .setSelected(false);
        jRadioButton_User.setSelected(false);
        jRadioButton_Table.setSelected(false);       
        
        ManagerRegisterForm manr = new ManagerRegisterForm();
        manr.setVisible(true);
        manr.pack();
        manr.setLocationRelativeTo(null);
        manr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jRadioButton_Managers_ActionPerformed

    private void jRadioButton_AntikeimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AntikeimActionPerformed
        jRadioButton_Evaluators_.setSelected(false);
        jRadioButton_Employees_.setSelected(false);
        jRadioButton_Managers_.setSelected(false);
        jRadioButton_Companies .setSelected(false);
        jRadioButton_User.setSelected(false);
        jRadioButton_Table.setSelected(false);
        
        AntikeimInsert anin = new AntikeimInsert();
        anin.setVisible(true);
        anin.pack();
        anin.setLocationRelativeTo(null);
        anin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jRadioButton_AntikeimActionPerformed

    private void jRadioButton_TableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_TableActionPerformed
        jRadioButton_Employees_.setSelected(false);
        jRadioButton_Companies.setSelected(false);
        jRadioButton_Antikeim.setSelected(false);
        jRadioButton_Companies.setSelected(false);
        jRadioButton_Evaluators_.setSelected(false);
        jRadioButton_User.setSelected(false);
        
        
        JComboBox jComboBox_Table = jComboBox_TableActionPerformed(evt);
        int input;
        input = JOptionPane.showConfirmDialog(this, jComboBox_Table, "Select ActionTable", JOptionPane.DEFAULT_OPTION);

        //get selected item from jcombobox
        if(input == JOptionPane.OK_OPTION){
            String table = jComboBox_Table.getSelectedItem().toString();
            
            ViewLogFileTable t_log = new ViewLogFileTable(table);
            t_log.setVisible(true);
            t_log.pack();
            t_log.setLocationRelativeTo(null);
            t_log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jRadioButton_TableActionPerformed
    
    private JComboBox jComboBox_TableActionPerformed(ActionEvent evt) {
        
        String[] actionTables = new String[] {"job", "employee", "requestsevaluation"};
 
        // create a combo box with the fixed array:
        JComboBox<String> jComboBox_Table = new JComboBox<String>(actionTables);
        jComboBox_Table.setFont(new java.awt.Font("Tahoma", 0, 14));
        
        return jComboBox_Table; 
    }
    
    private void jRadioButton_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_UserActionPerformed
        jRadioButton_Employees_.setSelected(false);
        jRadioButton_Companies.setSelected(false);
        jRadioButton_Antikeim.setSelected(false);
        jRadioButton_Companies.setSelected(false);
        jRadioButton_Evaluators_.setSelected(false);
        jRadioButton_Table.setSelected(false);
               
        JComboBox jComboBox_User = jComboBox_UserActionPerformed(evt);
        int input;
        input = JOptionPane.showConfirmDialog(this, jComboBox_User, "Select User", JOptionPane.DEFAULT_OPTION);

        //get selected item from jcombobox
        if(input == JOptionPane.OK_OPTION){
            String user = jComboBox_User.getSelectedItem().toString();
            
            ViewLogFileUser u_log = new ViewLogFileUser(user);
            u_log.setVisible(true);
            u_log.pack();
            u_log.setLocationRelativeTo(null);
            u_log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();

        }
    }//GEN-LAST:event_jRadioButton_UserActionPerformed

    private JComboBox jComboBox_UserActionPerformed(ActionEvent evt) {
        JComboBox jComboBox_User = new JComboBox();
        jComboBox_User.setFont(new java.awt.Font("Tahoma", 0, 14));
        
        PreparedStatement stm;
        ResultSet rs;
        String query = "select username from user";  
    
        try {
            stm = MySQLconnection.connectDb().prepareStatement(query);
            
            rs = stm.executeQuery();
            
            while(rs.next()){
                String username = rs.getString("username");
                jComboBox_User.addItem(username); // add into jComboBox
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        return jComboBox_User;
    }
    
    // Getters
    /*public static String getActionTable() {
      return actionTable;
    }
    
    public void setUser(String newUser) {
      this.user = newUser;
    }
  */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Back_;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose3;
    private javax.swing.JLabel jLabelMinim3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton_Antikeim;
    private javax.swing.JRadioButton jRadioButton_Companies;
    private javax.swing.JRadioButton jRadioButton_Employees_;
    private javax.swing.JRadioButton jRadioButton_Evaluators_;
    private javax.swing.JRadioButton jRadioButton_Managers_;
    private javax.swing.JRadioButton jRadioButton_Table;
    private javax.swing.JRadioButton jRadioButton_User;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    
}
