/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import javax.swing.JFrame;

/**
 *
 * @author filip
 */
public class MenuEvaluator extends javax.swing.JFrame {

    public static String EvaluatorUsername;
    
    public MenuEvaluator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelClose3 = new javax.swing.JLabel();
        jLabelMinim3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton_EvaluatorUpd = new javax.swing.JRadioButton();
        jRadioButton_AddJob = new javax.swing.JRadioButton();
        jRadioButton_ViewCompanyJobs = new javax.swing.JRadioButton();
        jButton_Back_ = new javax.swing.JButton();
        jRadioButton_InsertEvalData = new javax.swing.JRadioButton();
        jRadioButton_ViewEvaluation = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(248, 148, 6));

        jLabel4.setBackground(new java.awt.Color(236, 240, 241));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Evaluator Menu");

        jLabelClose3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabelClose3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose3.setText("X");
        jLabelClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose3MouseClicked(evt);
            }
        });

        jLabelMinim3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinim3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinim3.setText("-");
        jLabelMinim3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinim3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinim3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinim3)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabelClose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMinim3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(52, 73, 94));

        jRadioButton_EvaluatorUpd.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_EvaluatorUpd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_EvaluatorUpd.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_EvaluatorUpd.setText("View and edit your account informations");
        jRadioButton_EvaluatorUpd.setActionCommand("<html>\nChange the data of your company\n<br>\n(no AFM,DOY,name)\n</html>");
        jRadioButton_EvaluatorUpd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_EvaluatorUpd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_EvaluatorUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EvaluatorUpdActionPerformed(evt);
            }
        });

        jRadioButton_AddJob.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_AddJob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_AddJob.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_AddJob.setText("<html>\nAdd a new Job and insert all the necessary data\n<br>\n(and items in the antikeim table if they do not exist )\n</html>\n");
        jRadioButton_AddJob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_AddJob.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_AddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AddJobActionPerformed(evt);
            }
        });

        jRadioButton_ViewCompanyJobs.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_ViewCompanyJobs.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_ViewCompanyJobs.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_ViewCompanyJobs.setText("<html> View the data of the jobs announced in your company <br> and edit only those announced by you</html> ");
        jRadioButton_ViewCompanyJobs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_ViewCompanyJobs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_ViewCompanyJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ViewCompanyJobsActionPerformed(evt);
            }
        });

        jButton_Back_.setBackground(new java.awt.Color(242, 38, 19));
        jButton_Back_.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Back_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_Back_.setText("Back");
        jButton_Back_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back_ActionPerformed(evt);
            }
        });

        jRadioButton_InsertEvalData.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_InsertEvalData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_InsertEvalData.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_InsertEvalData.setText("<html>\nView the number of applications submitted for each job announced by you\n<br>\nand insert evaluation data in the jobs when submission date expires\n</html>\n\n\n");
        jRadioButton_InsertEvalData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_InsertEvalData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_InsertEvalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InsertEvalDataActionPerformed(evt);
            }
        });

        jRadioButton_ViewEvaluation.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_ViewEvaluation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_ViewEvaluation.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_ViewEvaluation.setText("<html>\nSelect one of the jobs you announced (for the 3.3 procedure)\n<br>\nand display all the results of the evaluation \n</html>\n\n");
        jRadioButton_ViewEvaluation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_ViewEvaluation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_ViewEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ViewEvaluationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 224, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_ViewEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton_AddJob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton_ViewCompanyJobs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton_EvaluatorUpd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButton_InsertEvalData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jRadioButton_EvaluatorUpd)
                .addGap(33, 33, 33)
                .addComponent(jRadioButton_ViewCompanyJobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton_AddJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton_InsertEvalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_ViewEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose3MouseClicked

    private void jLabelMinim3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinim3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinim3MouseClicked

    private void jRadioButton_EvaluatorUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EvaluatorUpdActionPerformed
        jRadioButton_AddJob.setSelected(false);
        jRadioButton_ViewCompanyJobs.setSelected(false);
        jRadioButton_InsertEvalData.setSelected(false);
        jRadioButton_ViewEvaluation.setSelected(false);
        

        EvaluatorUpd evupd = new EvaluatorUpd();
        evupd.setVisible(true);
        evupd.pack();
        evupd.setLocationRelativeTo(null);
        evupd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_EvaluatorUpdActionPerformed

    private void jRadioButton_AddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AddJobActionPerformed
        jRadioButton_EvaluatorUpd.setSelected(false);
        jRadioButton_ViewCompanyJobs.setSelected(false);
        jRadioButton_ViewEvaluation.setSelected(false);
        jRadioButton_InsertEvalData.setSelected(false);
        
        AddJob job= new AddJob();
        job.setVisible(true);
        job.pack();
        job.setLocationRelativeTo(null);
        job.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();              
    }//GEN-LAST:event_jRadioButton_AddJobActionPerformed

    private void jRadioButton_ViewCompanyJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ViewCompanyJobsActionPerformed
        jRadioButton_AddJob.setSelected(false);
        jRadioButton_ViewEvaluation.setSelected(false);
        jRadioButton_InsertEvalData.setSelected(false);
        jRadioButton_EvaluatorUpd.setSelected(false);

        ViewCompanyJobs cjobs = new ViewCompanyJobs();
        cjobs.setVisible(true);
        cjobs.pack();
        cjobs.setLocationRelativeTo(null);
        cjobs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_ViewCompanyJobsActionPerformed

    private void jButton_Back_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back_ActionPerformed
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_Back_ActionPerformed

    private void jRadioButton_InsertEvalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InsertEvalDataActionPerformed
        jRadioButton_EvaluatorUpd.setSelected(false);
        jRadioButton_AddJob.setSelected(false);
        jRadioButton_ViewEvaluation.setSelected(false);
        jRadioButton_ViewCompanyJobs.setSelected(false);
        
        InsertEvalData indata = new InsertEvalData();
        indata.setVisible(true);
        indata.pack();
        indata.setLocationRelativeTo(null);
        indata.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_InsertEvalDataActionPerformed

    private void jRadioButton_ViewEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ViewEvaluationActionPerformed
        jRadioButton_EvaluatorUpd.setSelected(false);
        jRadioButton_AddJob.setSelected(false);
        jRadioButton_ViewCompanyJobs.setSelected(false);
        jRadioButton_InsertEvalData.setSelected(false);
 
        ViewEvaluation veval = new ViewEvaluation();
        veval.setVisible(true);
        veval.pack();
        veval.setLocationRelativeTo(null);
        veval.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_ViewEvaluationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEvaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEvaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEvaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEvaluator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEvaluator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back_;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClose3;
    private javax.swing.JLabel jLabelMinim3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton_AddJob;
    private javax.swing.JRadioButton jRadioButton_EvaluatorUpd;
    private javax.swing.JRadioButton jRadioButton_InsertEvalData;
    private javax.swing.JRadioButton jRadioButton_ViewCompanyJobs;
    private javax.swing.JRadioButton jRadioButton_ViewEvaluation;
    // End of variables declaration//GEN-END:variables
}
