/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import javax.swing.JFrame;

/**
 *
 * @author filip
 */
public class MenuManager extends javax.swing.JFrame {

    /**
     * Creates new form MenuManager
     */
    
    
    public static String ManagerUsername;
    
    public MenuManager() {
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelClose3 = new javax.swing.JLabel();
        jLabelMinim3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton_CompDataChange_ = new javax.swing.JRadioButton();
        jRadioButton_ModifySalary_ = new javax.swing.JRadioButton();
        jRadioButton_PassEmailChange_ = new javax.swing.JRadioButton();
        jButton_Back_ = new javax.swing.JButton();
        jRadioButton_EvalRes_ = new javax.swing.JRadioButton();
        jRadioButton_AvgEvalGrade_ = new javax.swing.JRadioButton();
        jRadioButton_EmplFile_ = new javax.swing.JRadioButton();
        jRadioButton_EmplPrint_ = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(248, 148, 6));

        jLabel4.setBackground(new java.awt.Color(236, 240, 241));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manager Menu");

        jLabelClose3.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabelClose3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose3.setText("X");
        jLabelClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose3MouseClicked(evt);
            }
        });

        jLabelMinim3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinim3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinim3.setText("-");
        jLabelMinim3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinim3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinim3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinim3)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabelClose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMinim3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(52, 73, 94));

        jRadioButton_CompDataChange_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_CompDataChange_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_CompDataChange_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_CompDataChange_.setText("<html> Change the data of your company <br> (no AFM,DOY,name) </html>");
        jRadioButton_CompDataChange_.setActionCommand("<html>\nChange the data of your company\n<br>\n(no AFM,DOY,name)\n</html>");
        jRadioButton_CompDataChange_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_CompDataChange_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_CompDataChange_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_CompDataChange_ActionPerformed(evt);
            }
        });

        jRadioButton_ModifySalary_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_ModifySalary_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_ModifySalary_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_ModifySalary_.setText("Modify the salary of a job announced to your company");
        jRadioButton_ModifySalary_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_ModifySalary_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_ModifySalary_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ModifySalary_ActionPerformed(evt);
            }
        });

        jRadioButton_PassEmailChange_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_PassEmailChange_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_PassEmailChange_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_PassEmailChange_.setText("Change your password and email");
        jRadioButton_PassEmailChange_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_PassEmailChange_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_PassEmailChange_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PassEmailChange_ActionPerformed(evt);
            }
        });

        jButton_Back_.setBackground(new java.awt.Color(242, 38, 19));
        jButton_Back_.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Back_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_Back_.setText("Back");
        jButton_Back_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back_ActionPerformed(evt);
            }
        });

        jRadioButton_EvalRes_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_EvalRes_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_EvalRes_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_EvalRes_.setText("<html>\nDisplay the evaluation results for the positions of your company\n<br>\nthat they have finalize the evaluations\n</html>");
        jRadioButton_EvalRes_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_EvalRes_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_EvalRes_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EvalRes_ActionPerformed(evt);
            }
        });

        jRadioButton_AvgEvalGrade_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_AvgEvalGrade_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_AvgEvalGrade_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_AvgEvalGrade_.setText("<html> Display the average evaluation grade per evaluator <br> for every evaluator in your company </html>");
        jRadioButton_AvgEvalGrade_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_AvgEvalGrade_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_AvgEvalGrade_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AvgEvalGrade_ActionPerformed(evt);
            }
        });

        jRadioButton_EmplFile_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_EmplFile_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_EmplFile_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_EmplFile_.setText("<html>\nView and update the employee file\n<br>\n(sistatikes, certificates, awards)\n</html>");
        jRadioButton_EmplFile_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_EmplFile_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_EmplFile_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EmplFile_ActionPerformed(evt);
            }
        });

        jRadioButton_EmplPrint_.setBackground(new java.awt.Color(52, 73, 94));
        jRadioButton_EmplPrint_.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButton_EmplPrint_.setForeground(new java.awt.Color(236, 240, 241));
        jRadioButton_EmplPrint_.setText("<html>\nEnter the name and surname of an employee and print:\n<br> \n(a) His job applications\n<br>\n(b) His completed final evaluations \n<br>\n(c) The name and surname of the respective evaluator\n</html> ");
        jRadioButton_EmplPrint_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRadioButton_EmplPrint_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton_EmplPrint_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EmplPrint_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_AvgEvalGrade_, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton_EmplFile_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_EvalRes_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_ModifySalary_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_PassEmailChange_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_CompDataChange_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_EmplPrint_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jRadioButton_CompDataChange_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton_PassEmailChange_)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton_ModifySalary_)
                .addGap(32, 32, 32)
                .addComponent(jRadioButton_EvalRes_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton_AvgEvalGrade_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_EmplFile_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jRadioButton_EmplPrint_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton_Back_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClose3MouseClicked

    private void jLabelMinim3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinim3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinim3MouseClicked

    private void jRadioButton_CompDataChange_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_CompDataChange_ActionPerformed
        jRadioButton_ModifySalary_.setSelected(false);
        jRadioButton_PassEmailChange_.setSelected(false);
        jRadioButton_AvgEvalGrade_.setSelected(false);
        jRadioButton_EmplFile_.setSelected(false);
        jRadioButton_EmplPrint_.setSelected(false);
        jRadioButton_EvalRes_.setSelected(false);
        jRadioButton_CompDataChange_.setSelected(false);
        
        CompanyUpd comupd = new CompanyUpd();
        comupd.setVisible(true);
        comupd.pack();
        comupd.setLocationRelativeTo(null);
        comupd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_CompDataChange_ActionPerformed

    private void jRadioButton_ModifySalary_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ModifySalary_ActionPerformed
        jRadioButton_PassEmailChange_.setSelected(false);
        jRadioButton_AvgEvalGrade_.setSelected(false);
        jRadioButton_EmplFile_.setSelected(false);
        jRadioButton_EmplPrint_.setSelected(false);
        jRadioButton_EvalRes_.setSelected(false);
        jRadioButton_CompDataChange_.setSelected(false);

        ModifySalary ms = new ModifySalary();
        ms.setVisible(true);
        ms.pack();
        ms.setLocationRelativeTo(null);
        ms.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_ModifySalary_ActionPerformed

    private void jRadioButton_PassEmailChange_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PassEmailChange_ActionPerformed
        jRadioButton_ModifySalary_.setSelected(false);
        jRadioButton_AvgEvalGrade_.setSelected(false);
        jRadioButton_EmplFile_.setSelected(false);
        jRadioButton_EmplPrint_.setSelected(false);
        jRadioButton_EvalRes_.setSelected(false);
        jRadioButton_CompDataChange_.setSelected(false);

        PassEmailChange pec = new PassEmailChange();
        pec.setVisible(true);
        pec.pack();
        pec.setLocationRelativeTo(null);
        pec.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_PassEmailChange_ActionPerformed

    private void jButton_Back_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back_ActionPerformed
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_Back_ActionPerformed

    private void jRadioButton_EvalRes_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EvalRes_ActionPerformed
        jRadioButton_ModifySalary_.setSelected(false);
        jRadioButton_PassEmailChange_.setSelected(false);
        jRadioButton_AvgEvalGrade_.setSelected(false);
        jRadioButton_EmplFile_.setSelected(false);
        jRadioButton_EmplPrint_.setSelected(false);
        jRadioButton_CompDataChange_.setSelected(false);
        
        ShowEvalRes evres = new ShowEvalRes();
        evres.setVisible(true);
        evres.pack();
        evres.setLocationRelativeTo(null);
        evres.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_EvalRes_ActionPerformed

    private void jRadioButton_AvgEvalGrade_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AvgEvalGrade_ActionPerformed
        jRadioButton_ModifySalary_.setSelected(false);
        jRadioButton_PassEmailChange_.setSelected(false);
        jRadioButton_EmplFile_.setSelected(false);
        jRadioButton_EmplPrint_.setSelected(false);
        jRadioButton_EvalRes_.setSelected(false);
        jRadioButton_CompDataChange_.setSelected(false);
        
        EvalsAvg avgev = new EvalsAvg();
        avgev.setVisible(true);
        avgev.pack();
        avgev.setLocationRelativeTo(null);
        avgev.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_AvgEvalGrade_ActionPerformed

    private void jRadioButton_EmplPrint_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EmplPrint_ActionPerformed
        jRadioButton_ModifySalary_.setSelected(false);
        jRadioButton_PassEmailChange_.setSelected(false);
        jRadioButton_AvgEvalGrade_.setSelected(false);
        jRadioButton_EmplFile_.setSelected(false);
        jRadioButton_EvalRes_.setSelected(false);
        jRadioButton_CompDataChange_.setSelected(false);
        
        EmplPrint empr = new EmplPrint();
        empr.setVisible(true);
        empr.pack();
        empr.setLocationRelativeTo(null);
        empr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_EmplPrint_ActionPerformed

    private void jRadioButton_EmplFile_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EmplFile_ActionPerformed
        jRadioButton_ModifySalary_.setSelected(false);
        jRadioButton_PassEmailChange_.setSelected(false);
        jRadioButton_AvgEvalGrade_.setSelected(false);
        jRadioButton_EmplPrint_.setSelected(false);
        jRadioButton_EvalRes_.setSelected(false);
        jRadioButton_CompDataChange_.setSelected(false);
        
        EmplFile empf = new EmplFile();
        empf.setVisible(true);
        empf.pack();
        empf.setLocationRelativeTo(null);
        empf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jRadioButton_EmplFile_ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back_;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClose3;
    private javax.swing.JLabel jLabelMinim3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButton jRadioButton_AvgEvalGrade_;
    private javax.swing.JRadioButton jRadioButton_CompDataChange_;
    private javax.swing.JRadioButton jRadioButton_EmplFile_;
    private javax.swing.JRadioButton jRadioButton_EmplPrint_;
    private javax.swing.JRadioButton jRadioButton_EvalRes_;
    private javax.swing.JRadioButton jRadioButton_ModifySalary_;
    private javax.swing.JRadioButton jRadioButton_PassEmailChange_;
    // End of variables declaration//GEN-END:variables
}
